### ISSUE TITLE
Error: Systemd start for auditd failed!

### ISSUE THREAD

**Issue by WJ-8** [redhat-openstack/website#1438]
tar --dereference -cpzf - aodh apache ceilometer certmonger cinder concat firewall glance gnocchi heat horizon inifile ironic keystone magnum manila memcached mysql neutron nova nssdb openstack openstacklib oslo ovn packstack panko rabbitmq redis remote rsync sahara ssh stdlib swift sysctl tempest trove vcsrepo vswitch xinetd | ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@172.23.234.80 tar -C /var/tmp/packstack/730cdb1794dc484ab575802b3e14326e/modules -xpzf -
2023-10-11 15:47:42::ERROR::run_setup::1059::root:: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/packstack/installer/run_setup.py", line 1054, in main
    _main(options, confFile, logFile)
  File "/usr/lib/python2.7/site-packages/packstack/installer/run_setup.py", line 678, in _main
    runSequences()
  File "/usr/lib/python2.7/site-packages/packstack/installer/run_setup.py", line 645, in runSequences
    controller.runAllSequences()
  File "/usr/lib/python2.7/site-packages/packstack/installer/setup_controller.py", line 81, in runAllSequences
    sequence.run(config=self.CONF, messages=self.MESSAGES)
  File "/usr/lib/python2.7/site-packages/packstack/installer/core/sequences.py", line 109, in run
    step.run(config=config, messages=messages)
  File "/usr/lib/python2.7/site-packages/packstack/installer/core/sequences.py", line 50, in run
    self.function(config, messages)
  File "/usr/lib/python2.7/site-packages/packstack/plugins/puppet_950.py", line 214, in apply_puppet_manifest
    wait_for_puppet(currently_running, messages)
  File "/usr/lib/python2.7/site-packages/packstack/plugins/puppet_950.py", line 128, in wait_for_puppet
    validate_logfile(log)
  File "/usr/lib/python2.7/site-packages/packstack/modules/puppet.py", line 107, in validate_logfile
    raise PuppetError(message)
PuppetError: Error appeared during Puppet run: 172.23.234.80_controller.pp
Error: Systemd start for auditd failed!
You will find full trace in log /var/tmp/packstack/20231011-154545-7QuPZ9/manifests/172.23.234.80_controller.pp.log

**Comment by WJ-8** [comment]
[1;33mWarning: ModuleLoader: module 'ceilometer' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
   (file & line not available)[0m
[1;33mWarning: Scope(Class[Ceilometer::Agent::Central]): This class is deprecated. Please use ceilometer::agent::central with central namespace instead.[0m
[1;33mWarning: ModuleLoader: module 'redis' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
   (file & line not available)[0m
[1;33mWarning: ModuleLoader: module 'rabbitmq' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
   (file & line not available)[0m
[1;33mWarning: ModuleLoader: module 'oslo' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
   (file & line not available)[0m
[mNotice: Compiled catalog for laptop-tnv3bva4 in environment production in 5.55 seconds[0m
[1;31mError: Systemd start for auditd failed!
journalctl log for auditd:
Considering root directory '/run/log/journal'.
Considering root directory '/var/log/journal'.
Root directory /var/log/journal added.
No journal files were found.
Journal filter: ((OBJECT_SYSTEMD_UNIT=auditd.service AND _UID=0) OR (UNIT=auditd.service AND _PID=1) OR (COREDUMP_UNIT=auditd.service AND _UID=0 AND MESSAGE_ID=fc2e22bc6ee647b6b90729ab34a250b1) OR _SYSTEMD_UNIT=auditd.service)
Root directory /var/log/journal removed.
mmap cache statistics: 0 hit, 0 miss
